<a href="https://colab.research.google.com/github/cppel/data/blob/main/1_%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Практика Numpy

1. Скачайте этот блокнот к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература
- [**Блокнот с теорией**](https://clck.ru/35fwMP)
- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html


1) Импортировать numpy и написать версию

In [ ]:
import numpy as np
np.__version__

'1.23.5'

2) Создать нулевой вектор размера 10

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3) Создать вектор заполненный 7-ами размера 7

In [ ]:
vec = np.empty(7)
vec.fill(7)

print(vec, len(vec))

[7. 7. 7. 7. 7. 7. 7.] 7


4) Создать вектор заполненный четными числами от 10 до 100

In [ ]:
np.arange(10, 100, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [ ]:
out = np.random.rand(10)
print(out)

inverted = out[::-1]
print(inverted)

[0.05295468 0.36623761 0.6530164  0.92981051 0.82782576 0.38078217
 0.93796174 0.93290795 0.56953656 0.29312514]
[0.29312514 0.56953656 0.93290795 0.93796174 0.38078217 0.82782576
 0.92981051 0.6530164  0.36623761 0.05295468]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [ ]:
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [ ]:
np.eye(4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [ ]:
m = np.full((4,4), 7)
np.fill_diagonal(m, [1,2,3,4])
print(m)

[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [ ]:
np.full((5, 5), [0, 1,2,3,4])

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [ ]:
X = np.random.rand(10, 10)
print(X)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[0.4420447  0.87139249 0.41776498 0.74484193 0.11818273 0.11787252
  0.74959552 0.66602119 0.7235337  0.23492148]
 [0.39751752 0.47837962 0.61940977 0.84565726 0.97220167 0.07138254
  0.80162267 0.39623587 0.00459558 0.88043672]
 [0.74718368 0.94473427 0.2503993  0.63993199 0.10101541 0.82559029
  0.77320372 0.16661599 0.62672294 0.56611257]
 [0.6845255  0.98272958 0.50437692 0.89771574 0.74022297 0.44472682
  0.30034399 0.68478142 0.19079886 0.72217479]
 [0.9326078  0.95661542 0.62770222 0.29152741 0.90517142 0.91912438
  0.2125577  0.69457863 0.01404314 0.99367303]
 [0.50235093 0.09179997 0.82370282 0.73525049 0.28090513 0.89319244
  0.68302016 0.25540278 0.42510692 0.14308254]
 [0.09370801 0.99627519 0.96469753 0.06242305 0.34308394 0.78802355
  0.30899861 0.97679171 0.76609634 0.02441278]
 [0.24851971 0.67618514 0.206158   0.58438328 0.46433699 0.35654577
  0.58765881 0.29894523 0.32648424 0.62753968]
 [0.59577294 0.53282606 0.43007186 0.39964327 0.42453819 0.75185335
  0.99892528

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [ ]:
nums = np.random.rand(10, 10)
print("Original array elements:")
print(nums)

col_med = np.median(nums, axis=0)
print("median of each row:")
print(col_med)

print("\nSubtract the med of each row from each element:")
result = nums - col_med
print(result)

Original array elements:
[[0.16419612 0.00843135 0.88278772 0.9020149  0.79149423 0.69803371
  0.57416742 0.78560417 0.96465861 0.48095369]
 [0.26457959 0.12126978 0.82045361 0.80797071 0.97449005 0.22194767
  0.2453848  0.39892294 0.20369676 0.62464914]
 [0.34224116 0.54572546 0.95766976 0.03257493 0.9312189  0.99811002
  0.45553932 0.98464105 0.19063699 0.29570155]
 [0.45103047 0.67726972 0.72843495 0.61486652 0.3730614  0.31640361
  0.25719091 0.0914583  0.22962382 0.75501389]
 [0.39349711 0.02870406 0.30279806 0.98141702 0.53380555 0.22528794
  0.24208274 0.01655422 0.45500565 0.72766971]
 [0.36397377 0.58595049 0.95137515 0.04583278 0.16436118 0.83175388
  0.96045432 0.39108849 0.08590867 0.1458524 ]
 [0.29531317 0.83346506 0.90344225 0.18206706 0.57341324 0.01203006
  0.19809994 0.17382838 0.76898563 0.80567352]
 [0.50590204 0.85389022 0.25122637 0.26481504 0.06205289 0.90274504
  0.60666288 0.56142593 0.67412358 0.07024122]
 [0.21972075 0.88693027 0.17390639 0.62349799 0.1437243

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [ ]:
matr = np.arange(25).reshape((5, 5))
np.vstack([matr, np.min(matr, axis=1), np.max(matr, axis=1)])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [ 0,  5, 10, 15, 20],
       [ 4,  9, 14, 19, 24]])

13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [ ]:
a = np.arange(1,51)
print(a)

b = a[a % 2 == 1]
print(b)

print(len(b))

c = a[a % 2 == 0]
print(c)
print(len(c))

b_m = b.reshape(5, -1)
print(b_m)

c_m = c.reshape(5, -1)
print(c_m)

res_mul = b_m * c_m
print('mul:', res_mul)

print('inv:', np.linalg.inv(res_mul))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]
25
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]
25
[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]]
[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]]
mul: [[   2   12   30   56   90]
 [ 132  182  240  306  380]
 [ 462  552  650  756  870]
 [ 992 1122 1260 1406 1560]
 [1722 1892 2070 2256 2450]]


LinAlgError: ignored

14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [ ]:
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
